# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Scaling Behavior for Electric Vehicle Chargers and Road Map to Addressing the Infrastructure Gap
masthead_title: The EV Infrastructure Gap
email: venkvis@umich.edu
repository: BattModels/evse-scaling-behavior
baseurl: "/evse-scaling-behavior"
url: "https://BattModels.github.io"
name: "Alexius Wadell"

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-include-cache

analytics:
  provider: "google-gtag"
  google:
    tracking_id: G-XT01551W4K
    anonymize_ip: true

author:
  name: "Alexius Wadell"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: false
      related: false

footer:
  links:
    - label: "Github"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/BattModels/evse-scaling-behavior"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: https://www.linkedin.com/in/alexiuswadell/
